package IBM::MDM::LogAnalyzer::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'IBM::MDM::LogAnalyzer::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=mdm_analyzer',
        user => '',
        password => '',
    }
);

=head1 NAME

IBM::MDM::LogAnalyzer::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<IBM::MDM::LogAnalyzer>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<IBM::MDM::LogAnalyzer::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

Daniel Mantovani

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
